[project]
name = "lmcache-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bitsandbytes>=0.46.0",
    "lmcache>=0.3.1.post1",
    "transformers>=4.53.0",
    "vllm>=0.9.1",
]
